package com.xinmo.dao;

import com.xinmo.entity.Organization;
import com.xinmo.entity.OrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int countByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int deleteByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    List<Organization> selectByExampleWithBLOBs(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    List<Organization> selectByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    Organization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int updateByExampleWithBLOBs(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int updateByExample(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int updateByPrimaryKeyWithBLOBs(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_organization
     *
     * @mbggenerated Fri Apr 15 16:44:46 GMT+08:00 2016
     */
    int updateByPrimaryKey(Organization record);
}